### PR TITLE
Fix scripts

### LINKED ISSUE #6828: Magisk addon.d broken in 25211
Device: OnePlus 7 Pro & 9 Pro
Android version: 13
Magisk version name: 69529ac5
Magisk version code: 25211

Noted broken when taking my Lineage OTA today after updating from 25206 to 25211.

Not much time to test anything since 25211 yesterday until the release of 26000 15 minutes ago, so I'm investigating now and hopefully we can fix it in time for stable.

### PR DESCRIPTION
**Pull request by osm0sis**
manager.sh + boot_patch.sh:
- all listed files from boot_patch.sh header are required for boot patching, but stub.apk was being removed so install_magisk via addon.d.sh would fail without it; leave it in place

addon.d.sh:
- remove old redundant recovery_actions call (it's also performed by setup_flashable in initialize)
- print ABI to match flash_script.sh output

boot_patch.sh:
- catch and abort on any errors from ramdisk.cpio patching in the future

util_functions.sh:
- fix hiding of mount_partitions /system_root umount stderr
- quote mount_apex .pb DEST name parsing charset for safety even though both work

Fixes #6828

### CODE REVIEW

**Comment by vvb2060** [comment]
？？？？？？？？？？

File: scripts/boot_patch.sh [hunk 1]
```diff
@@ -173,7 +173,7 @@ if [ -n "$PREINITDEVICE" ]; then
   echo "PREINITDEVICE=$PREINITDEVICE" >> config
 fi
 [ -n "$SHA1" ] && echo "SHA1=$SHA1" >> config
-RANDOMSEED=$(tr -dc 'a-f0-9' < /dev/urandom | head -c 16)
+RANDOMSEED=$(tr -dc 'a-f0-8' < /dev/urandom | head -c 16)
```
Comment (yujincheng08) [inline scripts/boot_patch.sh:176]: ?

**Review by yujincheng08 — DISMISSED** [review]

File: scripts/boot_patch.sh (hunk 1 above)
Comment (osm0sis) [reply scripts/boot_patch.sh:176]: It's explained in the notes... It was suggested that was intended as a hex number by the 0x prefix in the next line, so I limited it correctly to the hexadecimal charset... I can remove that change if that's not what you actually wanted... 👍

Comment (yujincheng08) [reply scripts/boot_patch.sh:176]: so... hex numbers do not contain 9?

Comment (osm0sis) [reply scripts/boot_patch.sh:176]: Ah, right you are. My brain broke this evening. 😆

**Comment by ipdev99** [comment]
@topjohnwu
Can you review this PR and let us know what you think?

**Comment by osm0sis** [comment]
He's working on other PRs right now, I'm sure he'll get to it in due time.

**Review by topjohnwu — APPROVED** [review]

**Comment by MrLucifer92** [comment]
Thank you very much
