### PR TITLE
Don't always mock selinux enforce as "0"

### LINKED ISSUE #5607: Magiskinit causes `security_setenforce` fails with Invalid argument
Device: Realme 7 5G
Android version: 11
Magisk version name: Canary
Magisk version code: 24302

Upgrade and patch with or without vbmeta patch stock boot.img same error.
24301 was perfect
[magisk_install_log_2022-03-18T11_15_06[1].log](https://github.com/topjohnwu/Magisk/files/8303829/magisk_install_log_2022-03-18T11_15_06.1.log)
[magisk_install_log_2022-03-18T11_22_22[1].log](https://github.com/topjohnwu/Magisk/files/8303830/magisk_install_log_2022-03-18T11_22_22.1.log)

### PR DESCRIPTION
**Pull request by yujincheng08**
Some devices' SELinux will become enforced as soon as it loads sepolicy. And set it to enforcing again will crash `init`. So read the content again after sepolicy loaded and mock that result instead.

Fix #5607

### CODE REVIEW

File: native/jni/init/selinux.cpp [hunk 1]
```diff
@@ -169,6 +168,10 @@ void MagiskInit::hijack_sepolicy() {
     xmount("selinuxfs", REAL_SELINUXFS, "selinuxfs", 0, nullptr);
     sepol->to_file(REAL_SELINUXFS "/load");
 
+    if (strcmp(blocking_target, SELINUX_ENFORCE) == 0) {
```
Comment (topjohnwu) [inline native/jni/init/selinux.cpp:171]: Can you move this into the hijack lambda?

**Review by topjohnwu — APPROVED** [review]
