### PR TITLE
No kernel repack if it isn't patched at all 

### LINKED ISSUE #5124: Repacking kernel causes bootloop on many MT6763 devices
Device: Oppo F5 Youth (CPH1725)
Android version: 7.1.1
Magisk version name: 92546e8a
Magisk version code: 23016

Hello everyone, I tried to root my device using Magisk .But after flashed the patched boot.img, my device bootlooped, it's stuck at Oppo logo, and then resetting itself again. 😭

When I flashed the before Magisk patched boot.img, it returns to normal

Here I uploaded the `/proc/last_kmsg` and `/proc/mounts`. I also included the... non-stock boot.img I used to patch (contexts in the bottom of this post). But I also used the stock boot.img, it didn't work either.

~[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/7777169/last_kmsg.txt)~ (wrong last_kmsg)
[mounts.txt](https://github.com/topjohnwu/Magisk/files/7777173/mounts.txt)
[boot.zip](https://github.com/topjohnwu/Magisk/files/7777179/boot.zip)

---

Some contexts about this device,
* The firmware that I used is version A41
* I think I accidentally broke the i2c interface? The battery doesn't want to charge, the touchscreen didn't work
* The boot.img I attached was modified before patched by Magisk. But the bootloop is not caused by this, because the stock boot.img also didn't work
  * I moved the system and data partition out from eMMC to external microSD, so it make me easier to browse the filesystem when I don't have the root
  * Modification to force enable the OTG function (it's on "SMANKUSORS defined code" section)

### LINKED ISSUE #6204: Ulefone Power 3 - boot loop
## For humans

I tried to root this old device using the image patching technique but the phone ended up in a boot loop so I had to reflash the unpatched `boot.img`.

The phone is freshly reinstalled to stock (last update) official ROM.

As there is no separate vbmeta partition, I always checked `Patch vbmeta in boot image` option. I tried with both `Preserve force encryption` checked and unchecked. I did not tried to check `Preserve AVB 2.0/dm-verity`.

Note: It seems that the image patching technique was reported working back in the days when magisk was v7.5 (not 100% sure).

- Device: Ulefone Power 3
- Android version: 7.1.1
- Android security patch level: May 5, 2018
- Kernel version: `4.4.22+release@release32 #2 Fri Nov 24 19:25:19 CST 2017`
- Build Number: Power_3_G03
- Magisk version name: 25.2
- Magisk version code: 9b61bdfc (25201) (D)
- `/proc/mounts` logs: https://termbin.com/7t3w
- `/proc/last_kmsg`: https://termbin.com/j5jl
- unpatched `boot.img`: https://www36.zippyshare.com/v/gh1nvCpf/file.html
- boot ramdisk: yes
- separate vbmeta partition: no
- A/B (Seamless) System Updates: no

## For MagiskBot

Trying to make [MagiskBot](https://github.com/MagiskBot) happy (past fails #6202 #6203)

Device: Ulefone Power 3
Android version: 7.1.1
Magisk version name: 25.2
Magisk version code: 25201

### LINKED ISSUE #6566: Oppo A83 CPH1729 - bootloop
**I tried to root this old device using patch boot image technique but ended up bootlooping**

**These options are ticked when patching:**
- Preserve force encryption
- Patch vbmeta in boot image

**Some information about this device:**
- Device: Oppo A83
- Model: CPH1729
- Android version: 7.1.1
- Kernel version: 4.4.22-G202009032342
- Android Security Patch Level: October 5, 2019
- Magisk version name: 25.2 (25206)
- Magisk version code: 831a398b (25206) (D)
- Ramdisk: Yes
- A/B partition: No

**Files**

- Stock boot image: [here](https://drive.google.com/file/d/1NrAsuLtidvfgvBOvI2nN-QgkXxtswI13/view?usp=sharing)

- Patched boot image: [here](https://drive.google.com/file/d/1hZP0v8DIBkr8cDOj1U87kzNDRGesqKWH/view?usp=sharing)

- Log file after patching boot image: [here](https://drive.google.com/file/d/1QR5BVw6LX9RRdQyai1qWEtSQXARaoO7w/view?usp=sharing)

- Bug report file: [here](https://drive.google.com/file/d/1yMJCT3kd_gCxJnN5WbZAGPDBb0jNzMki/view?usp=sharing) (contains last_kmsg and dmesg)

- /proc/mounts: [here](https://drive.google.com/file/d/1Owx74615jPQv5NDIsPR-EZph6CI_QlOJ/view?usp=sharing)
___
Device: Oppo A83
Android version: 7.1.1
Magisk version name: 25.2
Magisk version code: 25206

### PR DESCRIPTION
**Pull request by canyie**
It turns out that decompressing and recompressing the kernel is enough to break booting on many devices that use MT6763.
So don't repack the kernel if it isn't patched.
As the kernel contains "skip_initramfs" but actually the device uses rootfs, we also need to check if the device is SAR before applying the SAR patch

Fix #5124, fix #6204, fix #6566

### CODE REVIEW

**Review by yujincheng08 — APPROVED** [review]

File: scripts/boot_patch.sh [hunk 1]
```diff
@@ -203,21 +204,28 @@ for dt in dtb kernel_dtb extra; do
...
+  # Force kernel to load rootfs for legacy SAR devices
   # skip_initramfs -> want_initramfs
-  ./magiskboot hexpatch kernel \
+  $SYSTEM_ROOT && ./magiskboot hexpatch kernel \
   736B69705F696E697472616D667300 \
-  77616E745F696E697472616D667300
+  77616E745F696E697472616D667300 \
+  && PATCHEDKERNEL=true
+  
+  # If the kernel doesn't need to be patched at all,
```
Comment (vvb2060) [inline scripts/boot_patch.sh:226]:
```suggestion
  && PATCHEDKERNEL=true

  # If the kernel doesn't need to be patched at all,
```

**Review by topjohnwu — APPROVED** [review]

**Comment by osm0sis** [comment]
Just occurred to me that this could leave a weird case if the kernel has a kernel_dtb, so perhaps someone can clarify; would a patched kernel_dtb replace the one attached to the untouched kernel in the .img (good), or would it just be appended to the untouched kernel, growing the kernel and boot.img size unnecessarily (bad)?

**Comment by osm0sis** [comment]
Found one edge case, which is when there's a replacement kernel file which is already compressed and has kernel_dtb attached, the existing kernel_dtb will just get appended to it, increasing the kernel+kernel_dtb size like I worried about.

I don't think this is an issue Magisk itself will run into, but other projects that use magiskboot (TWRP, kernel community, etc.) will; I'll see if I can address it with a patch to the `magiskboot split` applet or something. 👍
