### PR TITLE
Fix overflow

### LINKED ISSUE #4049: Segmentation fault during patching boot with integrated TWRP
Device: Xiaomi Mi A1
Android version: 9
Magisk version name: f152b4c2
Magisk version code: 22005

Yes, I know Magisk shouldn't be perfectly compatible with integrated TWRP in boot.img. But anyway, this behavior has not happened before 22000, I think.
If wontfix - it's OK, but maybe someone take a look at this.

boot.img: https://drive.google.com/file/d/1Huw6LPW3bCLrngckWUCu7aGdOx5Ht_Dx/view?usp=sharing
log:
```
- Target image: /dev/block/mmcblk0p23
- Device platform: arm64-v8a
- Installing: f152b4c2 (22005)
- Unpacking boot image
Parsing boot image: [/dev/block/mmcblk0p23]
HEADER_VER      [1]
KERNEL_SZ       [9866617]
RAMDISK_SZ      [18271145]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2020-08]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM        [b5a3f652ac387570269b5683ff05ae4004b3324e000000000000000000000000]
Segmentation fault
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
Parsing boot image: [/dev/block/mmcblk0p23]
- Repacking boot image
HEADER_VER      [1]
KERNEL_SZ       [9866617]
RAMDISK_SZ      [18271145]
SECOND_SZ       [0]
RECOV_DTBO_SZ   [0]
OS_VERSION      [9.0.0]
OS_PATCH_LEVEL  [2020-08]
PAGESIZE        [2048]
NAME            []
CMDLINE         [console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user veritykeyid=id:5560e7863b4d8118c2f1b065595cf93bb2447992]
CHECKSUM        [b5a3f652ac387570269b5683ff05ae4004b3324e000000000000000000000000]
Segmentation fault
! Unable to repack boot image!
! Installation failed

```

### PR DESCRIPTION
**Pull request by shakalaca**
Fix #4049

### CODE REVIEW

**Comment by osm0sis** [comment]
Is this sufficient to fix #4049?

**Comment by shakalaca** [comment]
oh yes, somehow the comments were lost .. lol

File: native/jni/magiskboot/bootimg.cpp [hunk 1]
```diff
@@ -205,12 +205,12 @@ static int find_dtb_offset(uint8_t *buf, unsigned sz) {
 
         // Check that fdt_header.totalsize does not overflow kernel image size
         uint32_t totalsize = fdt32_to_cpu(fdt_hdr->totalsize);
-        if (curr + totalsize > end)
+        if (totalsize > end - curr)
```
Comment (dwdjanika) [inline native/jni/magiskboot/bootimg.cpp:208]: #

**Review by dwdjanika — CHANGES_REQUESTED** [review]

**Review by topjohnwu — APPROVED** [review]
