### PR TITLE
Fix install regressions and a few other fixes/improvements

### LINKED ISSUE #3119: No full clean after customize.sh
It looks like module_installer.sh does not clean everything correctly when customize.sh with SKIPUNZIP=1 is used.

To reproduce it try the following:
1. Create a simple module with pure customize.sh file with only one string SKIPUNZIP=1. I have attached that one.
[test.zip](https://github.com/topjohnwu/Magisk/files/5152959/test.zip)
2. Install it.
3. Reboot.

In theory this addon simply does nothing and no new modules should appear in Magisk as well as no new folders should be created in /data/adb/modules/
But it is not true in practice - /data/adb/modules/ contains this new module.

1. Installation log file: 
[magisk_install_log_2020-09-01T01_40_54Z.log](https://github.com/topjohnwu/Magisk/files/5152968/magisk_install_log_2020-09-01T01_40_54Z.log)
Pay attention on cp error.
2. New module folder in /data/adb/modules/ (archived, in fact - contains empty update file only): 
[testtesttest.zip](https://github.com/topjohnwu/Magisk/files/5152972/testtesttest.zip)
3. New empty item in /data/adb/modules_update (archived, in fact - empty): 
[modules_update.zip](https://github.com/topjohnwu/Magisk/files/5152975/modules_update.zip)

Looks like some mechanism that should completely wipe off the module folder works incorrectly.

### LINKED ISSUE #3961: 64-bit detection not reliable
Hi,

d2bc2cfcf87e4506569b0c6904b6213297f45646 installs the 64-bit Magisk binary into the initramfs if it detects a `/system/lib64` directory. On my [TV](https://github.com/yath/tpm171e), however, the kernel is an `armv7l` one and cannot execute 64-bit binaries, yet there is a `/system/lib64` directory (with only an `arm64` `libnanovoice.so`, I dunno why that is :shrug:). This results in a `magisk64.xz` binary installed into the initrd, and init failing to execute it (“<11>[   58.786037] init: cannot execve('/sbin/magisk'): Exec format error”).

I don’t know of a good way to solve this, otherwise I’d send a PR. I guess the most reliable way (apart from guessing from `uname -m`) would be attempting to execute the 64-bit binary in `boot_patch.sh` and if it does not succeed, set `IS64BIT` to false. init could alternatively fall back to the 32-bit version if exec fails with `ENOEXEC`.

Thanks for your work!\
Sebastian

### PR DESCRIPTION
**Pull request by osm0sis**
scripts: clean up remaining Manager references

scripts: fix find_boot_image using wrong partition list on non-slot
- revert logic changes introduced by ec8fffe which break find_boot_image on NAND devices and any others using non-standard naming supported by the A-only device boot partition name list
- despite being accepted equivalents in modern shells -n does not work on Android in some shell/env scenarios where ! -z always does

scripts: add boot_patch unpack error catching
- failure to unpack wasn't being caught so boot_patch would continue to build a new cpio out of nothing and attempt to repack it (identified in #4049)

scripts: improve boot_patch 64bit detection
- use existing api_level_arch_detect function
Fixes #3961

App: add versionCode to magisk_patched.img filenames

scripts: fix empty module cleanup
- should be sufficient for all basic modules, see https://github.com/topjohnwu/Magisk/issues/3119#issuecomment-704000783 for ideas for fixing it further on the daemon module-processing side
Fixes #3119

### CODE REVIEW

**Review by dwdjanika — APPROVED** [review]
- [x]

File: app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt [hunk 1]
```diff
@@ -255,7 +255,7 @@ abstract class MagiskInstallImpl protected constructor(
                 val alpha = "abcdefghijklmnopqrstuvwxyz"
                 val alphaNum = "$alpha${alpha.toUpperCase(Locale.ROOT)}0123456789"
                 val random = SecureRandom()
-                val filename = StringBuilder("magisk_patched_").run {
+                val filename = StringBuilder("magisk_patched-${BuildConfig.VERSION_CODE}_").run {
```
Comment (vvb2060) [inline app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt:258]: `magisk_patched-`  → `magisk_patched_`

Comment (osm0sis) [reply app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt:258]: I've looked at it both ways and I think - looks better there:

magisk_patched_22005_31P8J.img
vs.
magisk_patched-22005_31P8J.img

Plus it matches the APK naming in a way: Magisk-f152b4c2(22005).apk

**Review by dwdjanika — APPROVED** [review]

**Review by topjohnwu — APPROVED** [review]

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/ndk-busybox/blob/android-ndk-1.34.1/coreutils/test.c

busybox supports -n

**Comment by osm0sis** [comment]
We've discussed this since in another PR or issue and discovered what the actual issue was with -n, yes
